### ISSUE TITLE
Browser REPL?

### ISSUE THREAD

**Issue by grammati** [martinklepsch/tenzing#11]
Hi Martin, the README says that tenzing includes a browser repl, like chestnut, but I have not been able to figure out how to connect to it. As far as I can tell, I should be able to just type `(start-repl)` in the cider REPL, but that does not work.

Would it be possible to add a couple of lines to the README explaining how to get the REPL working?

Thanks!

**Comment by martinklepsch** [comment]
@grammati after some recent changes to Clojurescript itself a lot of REPL tooling has been broken and the REPL inside Tenzing is affected by this.
I'll post an update here when it's working again. Should be some time this week.

**Comment by vvvvalvalval** [comment]
Same problem here. For the record, the exception I get is:

```
clojure.lang.ArityException: Wrong number of args (1) passed to: closure/get-upstream-deps*
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:32)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$memoize$fn__5097.doInvoke(core.clj:5846)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at weasel.repl.websocket$repl_env.doInvoke(websocket.clj:35)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at clojure.lang.Var.invoke(Var.java:430)
	at clojure.lang.AFn.applyToHelper(AFn.java:195)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.doInvoke(core.clj:632)
	at clojure.lang.RestFn.invoke(RestFn.java:660)
	at adzerk.boot_cljs_repl$weasel_connection.invoke(boot_cljs_repl.clj:49)
	at adzerk.boot_cljs_repl$repl_env.doInvoke(boot_cljs_repl.clj:82)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at adzerk.boot_cljs_repl$start_repl.doInvoke(boot_cljs_repl.clj:98)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at boot.user$eval5610.invoke(boot.user4340695587558959724.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6666)
	at clojure.core$eval.invoke(core.clj:2927)
	at clojure.main$repl$read_eval_print__6625$fn__6628.invoke(main.clj:239)
	at clojure.main$repl$read_eval_print__6625.invoke(main.clj:239)
	at clojure.main$repl$fn__6634.invoke(main.clj:257)
	at clojure.main$repl.doInvoke(main.clj:257)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__1258.invoke(interruptible_eval.clj:72)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1300$fn__1303.invoke(interruptible_eval.clj:188)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__1293.invoke(interruptible_eval.clj:157)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rej156** [comment]
Is this working yet?

**Comment by martinklepsch** [comment]
I just tested this with Emacs and `inf-clojure` and it worked fine. If you could test with your respective setups that would be a great help.

**Comment by rej156** [comment]
Getting the same error as those above and this.
https://github.com/adzerk/boot-cljs-repl/issues/8

**Comment by martinklepsch** [comment]
@rej156 please read my comment in the issue you referenced.

**Comment by vvvvalvalval** [comment]
I tried it with latest ClojureScript version (`[org.clojure/clojurescript "0.0-3058"]`) and it worked. Maybe we should included it explicitely in the dependencies to make it more stable?

**Comment by martinklepsch** [comment]
@vvvvalvalval probably a good idea. I'll pin it to `0.0-2814` as that's the minimum requirement I think.

**Comment by vvvvalvalval** [comment]
Sure, but make sure it's still in Clojars

**Comment by andreypopp** [comment]
I wasn't able to insyall `0.0-2814` from clojars for some reason but the latest `0.0-3058` works fine.

P.S. what do you think about including `cider-nrepl` in the template by default?

**Comment by martinklepsch** [comment]
Hm. That's weird. It seems to be available here: [mvnrepository.com](http://mvnrepository.com/artifact/org.clojure/clojurescript/0.0-2814).

@andreypopp you can add `cider-nrepl` to your `~/.profile.boot` as described here: https://github.com/boot-clj/boot/wiki/Cider-REPL — should not be a concern of this template imho.

**Comment by pandeiro** [comment]
@martinklepsch: do you get the "WARNING: Use of undeclared Var xxxx at line 1 <cljs repl>" in the REpl when referring to vars inside other namespaces (besides cljs.user) ? If so, do we know what's causing this?

**Comment by martinklepsch** [comment]
Huh, I thought I would not be able to replicate but happens for me as well. No idea why really. I saw occasional `undeclared Var` warnings every now and then but right now it just flooded my screen with them and didn't stop. Probably best to create a minimal test-case and open an issue in the `boot-cljs-repl` project.

**Comment by martinklepsch** [comment]
@pandeiro the following just worked fine for me... is that what we were talking about?
```boot.user=> (start-repl)
Writing boot_cljs_repl.cljs...
<< Started Weasel server on ws://127.0.0.1:0 >>
Type `:cljs/quit` to stop the ClojureScript REPL
Writing boot_cljs_repl.cljs...
nil
cljs.user=> (.log js/console "test")
nil
cljs.user=> (require 'repl-test.app)
nil
cljs.user=> (in-ns 'repl-test.app)
repl-test.app
repl-test.app=> (reagent/render-component [some-component] (.getElementById js/document "container"))
#<[object Object]>
nil
```

Source of `repl-test.app`:
```clojure
(ns repl-test.app
  (:require [reagent.core :as reagent :refer [atom]]))

(defn some-component []
  [:div
   [:h3 "I am a component!"]
   [:p.someclass
    "I have " [:strong "bold"]
    [:span {:style {:color "red"}} " and red"]
    " text."]])

(defn calling-component []
  [:div "Parent component"
   [some-component]])

(defn init []
  (reagent/render-component [calling-component]
                            (.getElementById js/document "container")))
```

**Comment by lvh** [comment]
@martinklepsch Does recompilation or evaling forms work correctly with that setup?

**Comment by martinklepsch** [comment]
@lvh it's working for me, might be different for you. Are you experiencing any issues?

**Comment by lvh** [comment]
I'll try it out; previously I was being hit by the fact that right now the most current versions of weasel & clojurescript don't play nicely together due to recent changes in how CLJS does repls.

**Comment by crisptrutski** [comment]
Just tried it out now, and didn't have success.

First, I had to add a bunch of extra dependencies to get things rolling - piggieback and weasel, adding tools.nrepl so ensure no mismatch. No dice, saw tip to update ClojureScript above, and went straight to head, also changing Clojure to 1.7.0-beta3 to support it.

Still ending up with an exception:

```
java.lang.NullPointerException:
boot.user=> *e
#error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.java.io$make_parents doInvoke "io.clj" 433]}]
 :trace
 [[clojure.java.io$make_parents doInvoke "io.clj" 433]
  [clojure.lang.RestFn invoke "RestFn.java" 410]
  [adzerk.boot_cljs_repl$make_repl_connect_file invoke "boot_cljs_repl.clj" 33]
  [adzerk.boot_cljs_repl$repl_env doInvoke "boot_cljs_repl.clj" 85]
  [clojure.lang.RestFn invoke "RestFn.java" 457]
```

Final dependencies added were:

```
                 [com.cemerick/piggieback "0.1.5"]
                 [org.clojure/tools.nrepl "0.2.10"]
                 [org.clojure/clojurescript "0.0-3269"]
                 [weasel "0.6.0"]
```

Not going to dig anymore in case I'm going down the wrong foxhole. Do we really need to add extra dependencies to start with, to get this command working with **tenzing**? 

(and if so - perhaps a generator option would be useful here to add them automatically)

**Comment by crisptrutski** [comment]
If this helps, just tried with ClojureScript `0.0.3058` as mentioned above (with Clojure 1.6 and 1.7 beta), and throwing the same exception.

**Comment by martinklepsch** [comment]
Not sure if this is going to help with anything but Piggieback 0.1.5 is
very old.
https://clojars.org/com.cemerick/piggieback

**Comment by crisptrutski** [comment]
Thanks for the spot - had tried latest piggie too though, just ended with a conservative version.

So I'm not barking up the wrong tree adding these dependencies in the first place? README sounds like it should "just work"

Here's a prettier stacktrace if it's helpful

```
java.lang.NullPointerException:
                clojure.java.io/make-parents                            io.clj:  433
                                         ...
adzerk.boot-cljs-repl/make-repl-connect-file                boot_cljs_repl.clj:   33
              adzerk.boot-cljs-repl/repl-env                boot_cljs_repl.clj:   85
                                         ...
            adzerk.boot-cljs-repl/start-repl                boot_cljs_repl.clj:   98
                                         ...
                         boot.user/eval12880  boot.user5275297083116157215.clj:    1
                                         ...
                           clojure.core/eval                          core.clj: 3079
```

**Comment by martinklepsch** [comment]
> So I'm not barking up the wrong tree adding these dependencies in the first place? README sounds like it should "just work" 

Now that I think about it you're right. It should just work. Dependencies should be imported via [boot-cljs-repl](https://github.com/adzerk-oss/boot-cljs-repl).

Running `boot show -d` might also be helpful in finding out about dependencies which are actually loaded after resolution.

**Comment by crisptrutski** [comment]
@martinklepsch thanks for confirming I'd gone astray - found my user issue.

Basically was using `boot repl` directly, so the `clj-repl` task was not being run in advance.

Using  `boot development cljs-repl repl`, or better `boot repl -c` with `boot dev` running have me all sorted.

Blundering first and then skimming a README too fast.. :hushed:

**Comment by martinklepsch** [comment]
@crisptrutski awesome — so you got it working and can evaluate stuff and all that? It'd be cool if you can give it a thorough test and report back. This issue needs to die :P

**Comment by crisptrutski** [comment]
- [x] Evaluate forms in the REPL
- [x] Cause side effects in the browser
- [x] Require cljsjs style dependency (did this indirectly - `(require '[matchbox.core :as m])`)
- [ ] Use the imported namespace

This is where things break down for me. It's been awhile since I've used a CJS repl, so perhaps "statement" style requires is not supported, but the error I get here is a bit strange:

```
=> (m/connect "<some-firebase-uri>")
clojure.lang.ExceptionInfo: #<ReferenceError: matchbox is not defined>
=> (println (.-stack *e))
ReferenceError: matchbox is not defined
    at eval (eval at <anonymous> (http://localhost:3000/js/out/weasel/repl.js:28:470), <anonymous>:1:69)
    at eval (eval at <anonymous> (http://localhost:3000/js/out/weasel/repl.js:28:470), <anonymous>:9:3)
    at http://localhost:3000/js/out/weasel/repl.js:28:465
    at http://localhost:3000/js/out/weasel/repl.js:37:4
    at cljs.core.MultiFn.call.G__11223__2 (http://localhost:3000/js/out/cljs/core.js:31221:113)
    at cljs.core.MultiFn.call.G__11223 [as call] (http://localhost:3000/js/out/cljs/core.js:31925:20)
    at null.<anonymous> (http://localhost:3000/js/out/weasel/repl.js:137:71)
    at goog.events.EventTarget.fireListeners (http://localhost:3000/js/out/goog/events/eventtarget.js:284:23)
    at Function.goog.events.EventTarget.dispatchEventInternal_ (http://localhost:3000/js/out/goog/events/eventtarget.js:381:26)
    at goog.events.EventTarget.dispatchEvent (http://localhost:3000/js/out/goog/events/eventtarget.js:196:34)
```

**Comment by crisptrutski** [comment]
Tried `(require '[cljsjs.firebase])` directly, and similar result - the statement succeeds, but no `js/Firebase` global is created

**Comment by martinklepsch** [comment]
@crisptrutski dude, awesome. Thanks for the clear writeup. I think thats where things broke for me last time as well. Are you on the very latest `boot-cljs`? (just for the record not sure if that'd change anything)

**Comment by crisptrutski** [comment]
Bumped from `0.0-2814-4` to `0.0-3269-0`, and seeing the same issue.

I'm off now, but will come back and poke at this - tantalizingly close!

**Comment by martinklepsch** [comment]
Great. Maybe @myguidingstar has some ideas as well, he has been doing some work on `boot-cljs-repl` recently.

**Comment by martinklepsch** [comment]
https://github.com/modnakasta/boot-cljs-repl — this might be an option to try.

**Comment by crisptrutski** [comment]
Somehow missed how old the version of CLJS in boot-cljs-repl was. This makes total sense now - and I'm glad to announce:

- [x] Use the imported namespace

One gotcha is that the "wrong tools.nrepl" resolution snafoo affected me - but can probably fix that by adding `[org.clojure/tools.nrepl "0.2.10"]` upstream in `boot-cljs-repl` (rather than adding another primary dependency to `tenzing` output)

Should `tenzing` switch to this `boot-cljs-repl` fork for now?

**Comment by crisptrutski** [comment]
Oh wait, bad test - the require was not really tested as the module was already loaded in the app I connected to :trollface: 

```
cljs.user=> (require 'cljsjs.firebase)
cljs.user=> js/Firebase
#<ReferenceError: Firebase is not defined>
```

**Comment by martinklepsch** [comment]
> Somehow missed how old the version of CLJS in boot-cljs-repl was.

I think usually boot-cljs-repl should pick up the clojurescript version that's defined in your project — hasn't that been the case for you? (If you run with `boot -vv` you can see the versions of relevant deps printed as a debug message).

**Comment by crisptrutski** [comment]
You're right, the task pod is being polite it seems https://github.com/modnakasta/boot-cljs-repl/blob/master/src/adzerk/boot_cljs_repl.clj#L20

**Comment by martinklepsch** [comment]
Hey everyone, good news! Once https://github.com/adzerk-oss/boot-cljs-repl/pull/18 is merged and you've updated to it and a recent CLJS version the REPL will work. I just tested it and it's working great! :+1:

**Comment by crisptrutski** [comment]
Upstream fixes are in, this "just works" :tm:
