### ISSUE TITLE
$ boot dev fails with:

### ISSUE THREAD

**Issue by dviramontes** [martinklepsch/tenzing#18]
`clojure.lang.ExceptionInfo: dbug does not exist`

`data: {:file "adzerk/boot_cljs.clj", :line 1}`

`java.lang.IllegalAccessError: dbug does not exist`

$ ~/local/../.. javac -version
**javac 1.7.0_67**
$ ~/local/../.. java -version
**java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)**

OS: mac os 10.9 , I'm happy to share the full stack trace.
Just let me know. Wondering if I'm doing something 
wrong on my end.

**Comment by martinklepsch** [comment]
Please make sure your version of Boot is [up to date](https://github.com/boot-clj/boot/wiki/Keeping-Boot-Up-to-Date).

Also please paste your `build.boot` file if updating didn't fix the issue :)

**Comment by dviramontes** [comment]
`boot -u `
did the trick :) 
thanks !
