### ISSUE TITLE
+hoplon Option?

### ISSUE THREAD

**Issue by Quasaur** [martinklepsch/tenzing#20]
Your Video from January was an eye-opener; i am so grateful that you took the time to present such valuable information!

I'm also grateful that you've included so many useful options...could you please add a hoplon option?

Thank you!

Calvin

**Comment by martinklepsch** [comment]
@Quasaur Hey! Sorry for not replying earlier. 

I think providing a Hoplon option would be really nice and would welcome any efforts in that direction. That said I currently don't have the time to do it myself. If you're familiar with Hoplon or at least know what's needed to provide such option I'd like to encourage you to just give it a spin, adding it yourself and making a pull request. If you need any help in the process I'm happy to see how I can  support this :)

**Comment by Quasaur** [comment]
Don't know if I'm that good; but I'm working on it (grin)...thanks for the reply!
