### ISSUE TITLE
new project fails to run

### ISSUE THREAD

**Issue by led** [martinklepsch/tenzing#23]
Just following the instructions to set up a new vanilla project. With nothing edited, when I run 'boot dev' I get…
```
  clojure.lang.ExceptionInfo: dbug does not exist
    data: {:file "adzerk/boot_cljs.clj", :line 1}
java.lang.IllegalAccessError: dbug does not exist
                     clojure.core/refer                          core.clj: 3919
etc
```
I'm not really sure where to take it from there? Any clues?

**Comment by martinklepsch** [comment]
Hey @led — thanks for the report!

What version of `boot-cljs` is listed in your `build.boot` file?

**Comment by led** [comment]
I used 'lein ancient' to check it was the latest versions of everything…

[adzerk/boot-cljs      "0.0-2814-4" :scope "test"]

**Comment by martinklepsch** [comment]
I think the issue might be that Boot itself is outated and not so much `boot-cljs`. 

What do the first 3 lines of `boot -h` look like?

**Comment by led** [comment]
Ah! <wince> Yes indeed - thank you! It was an outdated version that simply wasn't running at all. As I haven't used it until now, I'd forgotten I'd installed it a while back and that it wasn't updated in any way. Now to test out Tenzing!

Many thanks.

**Comment by martinklepsch** [comment]
You're welcome! Have fun and let me know if you run into any other issues :)
