### ISSUE TITLE
local server routes

### ISSUE THREAD

**Issue by ioRekz** [martinklepsch/tenzing#24]
Hi,
I'm using divshot to deploy my app (I discover it thanks to you).
I'm using the routes key in divshot.json
```
"routes": {
    "*": "index.html"
  },
```
I also need some more custom route for some images.
Any idea how I could configure the local app to allow such routes ?

**Comment by martinklepsch** [comment]
Probably best to consult the official Divshot documentation for that:
https://docs.divshot.com/guides/routing

**Comment by ioRekz** [comment]
I need it for my local dev server.
Anyway I figured out this has to do with boot http and you answered me
