### ISSUE TITLE
Testing boilerplate

### ISSUE THREAD

**Issue by crisptrutski** [martinklepsch/tenzing#27]
Generating a harness for unit and/or integration tests would be useful!

**Comment by martinklepsch** [comment]
You mean adding the boilerplate to write application tests or testing what
the template generates and if it works?

First is definitely something worth adding, second is a bit harder and
probably it's more useful to write tests for the individual projects
containing task definitions.

**Comment by crisptrutski** [comment]
The first one, application boilerplate. Was actually hoping to come and some setup code from here, and that's when I noticed it was missing :cry:. Don't see much activity with https://github.com/boot-cljs-test/node-runner or https://github.com/boot-cljs-test/node-runner though. How are people testing CLJS with Boot 2 on CI these days?

Re: the latter, are you metacircularly suggesting to test the generated projects is test all the combinations including a test runner, and then test the test reporter outputs? Sounds like more fun than value though ;)

**Comment by martinklepsch** [comment]
I recently saw an announcement for "doo" on the mailing list. Maybe that's
something worth looking into.

Yes basically that's the idea. It has been discussed for chestnut as well
where it's actual to a bit more important than in tenzing because all
configuration things are intertwined.

Getting a test running thing into tenzing is definitely a better use of
anyone's time :)

**Comment by crisptrutski** [comment]
"Doo" is exactly what I'm looking for. Which mailinglist was that touted on - Clojurescript? Missed it somehow

**Comment by martinklepsch** [comment]
Yep: https://groups.google.com/forum/m/#!topic/clojurescript/ZZHl_HJ0KUs

You already see how it could be used with boot?

**Comment by crisptrutski** [comment]
My boot-foo is weak, but it looks like most of the lein plugin is implementing a pod anyway (creates a new project dynamically) https://github.com/bensu/doo/blob/master/plugin/src/leiningen/doo.clj, and the inner library seems agnostic enough.

Will roll up my sleeves and give it a go :)

**Comment by martinklepsch** [comment]
Awesome! There are many people wanting this :)

**Comment by crisptrutski** [comment]
Not sure if you want to close this yet, or still sort some of the niggles mentioned in #28

**Comment by martinklepsch** [comment]
Close it and open issues for the things that should be fixed/improved.
