### ISSUE TITLE
Update to CLJS 0.0-3308

### ISSUE THREAD

**Issue by crisptrutski** [martinklepsch/tenzing#29]
Despite the requirement on Clojure 1.7, it would be good to track `boot-cljs` while tools are still in flux. As one example, the tmp-file warnings are coming from the old version of `boot-cljs`, and are likely to distract new users.

Anecdotally, also finding that the phantomjs test runner via doo (#28) hangs with boot-cljs `0.0-2814-4` and works perfectly with `0.0-3308-0`.

**Comment by martinklepsch** [comment]
Updating to 33.. something makes perfect sense to me.
