### ISSUE TITLE
the template for reagent doesn't work with kioo

### ISSUE THREAD

**Issue by wqhhust** [martinklepsch/tenzing#36]
I create a template for reagent using command:
lein new tenzing reagent +reagent

Then in the boot.build, add the dependency of kioo.
```clj
(set-env!
 :source-paths    #{"src/cljs"}
 :resource-paths  #{"resources"}
 :dependencies '[[adzerk/boot-cljs      "0.0-2814-4" :scope "test"]
                 [adzerk/boot-cljs-repl "0.1.9"      :scope "test"]
                 [adzerk/boot-reload    "0.2.4"      :scope "test"]
                 [pandeiro/boot-http    "0.6.1"      :scope "test"]
                 [kioo "0.4.0"] 
                 [reagent "0.5.0"]])
```
But it throw the following error when run boot, after I remove  [kioo "0.4.0"]  in the  dependencies section, it goes back to normal. Could you please add the support for kioo?
boot/reagent $ boot dev
temp-dir! was deprecated, please use tmp-dir! instead
Writing boot_cljs_repl.cljs...
<< started reload server on ws://localhost:34279 >>
Writing boot_reload.cljs...
WARNING: Different CLJS version via transitive dependency: 0.0-2156
2015-07-19 17:09:22.280:INFO:oejs.Server:jetty-7.6.13.v20130916
2015-07-19 17:09:22.314:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:3000
<< started Jetty on http://localhost:3000 >>

Starting file watcher (CTRL-C to quit)...

clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException: No single method: _setup of interface: cljs.repl.IJavaScriptEnv found for function: -setup of protocol: IJavaScriptEnv, compiling:(cemerick/piggieback.clj:150:5)
     java.lang.IllegalArgumentException: No single method: _setup of interface: cljs.repl.IJavaScriptEnv found for function: -setup of protocol: IJavaScriptEnv
                                 ...

**Comment by martinklepsch** [comment]
It seems that kioo has a transitive dependency on Clojurescript. If you exclude Clojurescript like this it could work:
```
[kioo "0.4.0" :exclusions [org.clojure/clojurescript]]
```

**Comment by crisptrutski** [comment]
This exclusion should not even be necessary now that cljs is an explicit dependency #39
