### ISSUE TITLE
front page errors

### ISSUE THREAD

**Issue by yatesco** [martinklepsch/tenzing#37]
The front page has a few issues:

 - the first link to Tenzing goes to 404
 - the title appears twice
<img width="1438" alt="screen shot 2015-07-23 at 15 22 59" src="https://cloud.githubusercontent.com/assets/181469/8852733/d6ce7a24-314e-11e5-9d4c-e73cbae4ad4f.png">

**Comment by martinklepsch** [comment]
Thanks for the heads up, much appreciated! I use the Readme orgfile to generate http://martinklepsch.github.io/tenzing/ and that's mostly the reason why there are two headings. I'm slowly coming to the conclusion that this is probably not worth it though so I'll probably go back to a regular README.

**Comment by crisptrutski** [comment]
Closing this due to 99fa7fecdef78ae0a0525c9b61a2409a7e640033 :smile:
