### ISSUE TITLE
New project fails

### ISSUE THREAD

**Issue by jackrusher** [martinklepsch/tenzing#38]
Using a fresh version of boot:

```
#https://github.com/boot-clj/boot
#Mon Jul 27 12:46:53 CEST 2015
BOOT_CLOJURE_VERSION=1.6.0
BOOT_VERSION=2.0.0-rc14
#App version: 2.0.0
```

Creating a new project, like:

```
$ lein new tenzing hallo-martin +reagent
Generating fresh 'lein new' tenzing project.
```

... results in failure:

```
$ cd hallo-martin/
$ boot
clojure.lang.ExceptionInfo: Unable to resolve symbol: tmp-path in this context
   data: {:file "adzerk/boot_reload.clj", :line 22}
java.lang.RuntimeException: Unable to resolve symbol: tmp-path in this context
                    ...
   clojure.core/load/fn                          core.clj: 5866
      clojure.core/load                          core.clj: 5865
                    ...
  clojure.core/load-one                          core.clj: 5671
clojure.core/load-lib/fn                          core.clj: 5711
  clojure.core/load-lib                          core.clj: 5710
                    ...
     clojure.core/apply                          core.clj:  632
 clojure.core/load-libs                          core.clj: 5749
                    ...
     clojure.core/apply                          core.clj:  632
   clojure.core/require                          core.clj: 5832
                    ...
      boot.user/eval248  boot.user6554720971515145768.clj:   17
                    ...
     boot.main/-main/fn                          main.clj:  158
        boot.main/-main                          main.clj:  158
                    ...
       boot.App.runBoot                          App.java:  231
          boot.App.main                          App.java:  338
```

**Comment by jackrusher** [comment]
I have contacted the maintainer about this issue, but his response was that "Basically this is a problem with the version of Boot you're using" and a link to this page: [https://github.com/boot-clj/boot/wiki/Keeping-Boot-Up-to-Date](https://github.com/boot-clj/boot/wiki/Keeping-Boot-Up-to-Date), which sadly doesn't provide *any* useful information for resolving this problem (as he did not tell me version of Boot one is supposed to use with Tenzing).

**Comment by crisptrutski** [comment]
Hi @jackrusher 

The failing call indicates that you just need `2.0.0` as a minimum version. 

To quote from the release notes:

```
  * #128 refactor core api; renamed the following:
      - temp-dir! --> tmp-dir!
      - tmpdir    --> tmp-dir
      - tmpfile   --> tmp-file
      - tmppath   --> tmp-path
      - tmpfile?  --> tmp-file?
```

Are you still having issues after running `boot -u`?

**Comment by crisptrutski** [comment]
If `boot -u` is not updating you from `2.0.0-rc14` then I'd suggest opening an issue at https://github.com/boot-clj/boot

**Comment by jackrusher** [comment]
> The failing call indicates that you just need 2.0.0 as a minimum version.

^ is the useful piece of information required to know the version to which one should update. Having performed the upgrade, all is working (though with some warnings about deprecated variables -- should I file a ticket about that?).

**Comment by crisptrutski** [comment]
Great, glad you're unblocked!

To be honest I dig up the version quickly only because I remembered the commit - there's no changelog for in the boot repo, and info is only on the version commits, not in https://github.com/boot-clj/boot/releases. Not sure if they're keeping a good index, and its certainly not discoverable enough.

The warnings you're seeing due to out of date dependencies in the project, like `boot-cljs-repl` I believe. Think these may already be solved in a pending release of Tenzing, but a ticket won't hurt.

**Comment by crisptrutski** [comment]
To solve your own itch with the warnings, just use `boot show -u` to find the straggler versions in your new project

**Comment by martinklepsch** [comment]
> as he did not tell me which version of Boot one is supposed to use with Tenzing

@jackrusher I meant to imply that most recent version should work. Should have been more clear.

The important point here is that Boot has two components: 1) a slim binary that you put into your `$PATH` as `boot` and 2) a couple of jars providing most of the functionality.

While the `boot` binary has been up to date in this case the jars were out of date.
