### ISSUE TITLE
Should missing dependencies be warned or provided?

### ISSUE THREAD

**Issue by talexand** [martinklepsch/tenzing#45]
I noticed that you can start a project with `+sass` without having libsass completely set up; it will naturally fail when it gets to the sass compilation step (until [you build sassc](https://github.com/sass/sassc/blob/master/docs/building/unix-instructions.md)).

Would it be helpful to have a warning message or an automatic bundling of deps if options like `+sass` are chosen?

**Comment by crisptrutski** [comment]
At first I though "this sounds like something to take up at https://github.com/mathias/boot-sassc", but then I thought perhaps your asking for this warning at *project generation time*, ie. to add some boilerplate instructions related to particular options, that print out once the project is created?

That sounds OK, perhaps you would like to take a stab at writing the copy? :smile:

**Comment by talexand** [comment]
wow I don't even know where it would go in the code; the cljs build process is still magic to me. But something like

> Libsass was not detected on your machine. Please note that builds will fail until you configure a SASS compiler like `sassc` and place it in your PATH variable.

would be fine.
