### ISSUE TITLE
+electron task template

### ISSUE THREAD

**Issue by du5t** [martinklepsch/tenzing#55]
https://github.com/Gonzih/cljs-electron seems like a really nice setup for electron development, but i really like tenzing.

from a quick glance at the [project.clj](https://raw.githubusercontent.com/Gonzih/cljs-electron/master/project.clj) file there, it looks like the main build tasks that make it tick are builds by filetype to the public folder, but i haven't gone much deeper into it yet.

what else would it take on the tenzing side?

-----

edit: it looks like https://github.com/martinklepsch/electron-and-clojurescript is a good place to start from, so i guess i just need to go through the tenzing templates and work from there.

**Comment by martinklepsch** [comment]
He, I was just going to link to that :)

The setup is a bit more complex and I'm not sure if I want to put all of that into tenzing.

I'll close this for now, let me know if you have other questions
