### ISSUE TITLE
Divshot is dead.

### ISSUE THREAD

**Issue by jarcane** [martinklepsch/tenzing#56]
Divshot has [incredible-journeyed:](https://divshot.com/)

> Divshot has joined the Firebase team at Google! Firebase is a comprehensive suite of products for developers offered by Google, and by joining our vision with theirs, Divshot's mission continues onward at a grander scale!
> Firebase Hosting is Firebase's static web hosting service and is now powered in part by Divshot technology. However, all existing Divshot products including static web hosting and Divshot Architect have now shut down.

Probably not much use for the hooks anymore and the suggestion in the README is rather unhelpful since it now just points to that page.

**Comment by ioRekz** [comment]
I discovered Divshot thanks to tenzing and it helped me getting started. I'm currently using s3 website but I would recommend checking out surge.sh as it is a one liner to deploy statics website and a perfect replacement for divshot

**Comment by martinklepsch** [comment]
I was something similar to s3-website which I'm using for my sites, and other projects: https://github.com/confetti-clj/confetti — you might want to give that a spin as well :)

> Divshot has incredible-journeyed:

👍  on the wording haha. 

Of course a PR updating the readme, removing divshot related stuff etc would be most welcome.

**Comment by martinklepsch** [comment]
Closed via #57
