### ISSUE TITLE
README.md: boot implicit target directory creation no longer exists, i.e., no files to copy

### ISSUE THREAD

**Issue by gamecubate** [martinklepsch/tenzing#60]
Per README.md, ```Since Tenzing comes without a backend you can easily deploy your app to Amazon S3 or even host it in your Dropbox. To do that just copy the files in target/ to your desired location.```

Unfortunately, boot no longer does implicit target directory creation, which means that these instructions fail.

**Comment by martinklepsch** [comment]
Good catch! :) a PR updating those instructions would be welcome :+1:

**Comment by gamecubate** [comment]
Would love to update them but I am stuck trying to get boot to save compilation output to a js file. Something not clear on their side. If you leave this open, I will submit a PR once I've got the problem solved and some key concepts further understood.

**Comment by j1mr10rd4n** [comment]
The implicit `target` task has been deprecated but not removed yet. At the moment boot only skips the implicit call if `BOOT_EMIT_TARGET=no` has been set in `boot.properties`, either in the project root or in `~/.boot/boot.properties`.

In any case - #63 adds an explicit call to `target` and should fix this issue.

**Comment by j1mr10rd4n** [comment]
P.S. @gamecubate. If you haven't seen it yet - check out [Mimmo Cosenza's excellent tutorial](https://github.com/magomimmo/modern-cljs). It uses boot throughout and covers a lot of key concepts.

**Comment by gamecubate** [comment]
Oh but I hadn't seen that. Started reading. Perfect. Thanks for the nudge. :)

**Comment by martinklepsch** [comment]
@j1mr10rd4n a link to Mimmo's tutorial, especially the boot related bits might be a good addition to the readme. What do you think?

**Comment by j1mr10rd4n** [comment]
Sounds good to me, it's a great tutorial. What about [here](https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-02.md#introduction) as an entry point?
