### ISSUE TITLE
Source and release out of sync?

### ISSUE THREAD

**Issue by j1mr10rd4n** [martinklepsch/tenzing#61]
This repository's [project.clj](https://github.com/martinklepsch/tenzing/blob/master/project.clj#L1) has version 0.3.5-SNAPSHOT but the [latest available release on clojars](https://clojars.org/tenzing/lein-template/versions/0.3.6) is 0.3.6. The release was pushed with [commit 1e65002](https://github.com/martinklepsch/tenzing/commit/1e650023b971478202df552c25ad510a087ee6f8) but this isn't on github.

It looks like maybe a release was cut locally without pushing changes to the remote repo? I'd like to create a PR and it'd be easier to work against the latest code - thanks!

**Comment by martinklepsch** [comment]
@j1mr10rd4n sorry about that, just pushed :)
