### ISSUE TITLE
+cljs-devtools option

### ISSUE THREAD

**Issue by martinklepsch** [martinklepsch/tenzing#73]
https://github.com/jupl/boot-cljs-devtools has been working excellently for me and would be a great addition I think.

**Comment by pepe** [comment]
I would also like to add https://github.com/binaryage/dirac in to the mix. Both working really good together for me. Much better than with lein and figwheel. 

So I will try to create PR for this? I am still quite noob with leiningen templates, but learn or die, as they say.

And I like tenzing a lot, thanks for your work!

**Comment by martinklepsch** [comment]
Hey @pepe, glad you like Tenzing, always nice to hear :)

I'd be happy about a PR but would prefer if users can opt into devtools and dirac individually as dirac is a bit more advanced territory and some might end up more confused than enabled :)

**Comment by pepe** [comment]
I like the individual options better also. Thanks.

**Comment by pepe** [comment]
Well it seem taht [boot-cljs-devtools](https://github.com/boot-clj/boot-cljs-devtools) are all or nothing ;). So maybe let's try it the full way, And if it goes wrong, think about forking [boot-cljs-devtools](https://github.com/boot-clj/boot-cljs-devtools)?

**Comment by martinklepsch** [comment]
There's an issue/PR in the boot-cljs-devtools project about splitting the task up: https://github.com/boot-clj/boot-cljs-devtools/pull/3

If you're interested in tackling this I'm happy to provide some guidance otherwise I can also try to find some time to do (I've been meaning to do it for a long time anyways :))

**Comment by pepe** [comment]
Well my xmas challenge it could be ;).

I will try to ping you on Riot, if I'll get into troubles. Yday I did the easy/full way here https://github.com/pepe/tenzing/commit/bd2ff316f399b8621ccfbd5d9f46d71af281b564 if you like to look at it.

Thank you very much!

**Comment by pepe** [comment]
Just for the info: I made pull request https://github.com/boot-clj/boot-cljs-devtools/pull/7, where tasks for cljs-devtools and dirac are separated.

**Comment by pepe** [comment]
Hello, as you know I actually scored that task separating PR on boot-cljs-devtools ;). And new snapshot was released, so I will try tonite finish this with it.

**Comment by martinklepsch** [comment]
Closing. #76 has all changes to support devtools and dirac options.
