### ISSUE TITLE
Where does the name Tenzing coming from? 

### ISSUE THREAD

**Issue by Cka3** [martinklepsch/tenzing#79]
subj. Just wondering why tenzing? Is it this one https://en.wikipedia.org/wiki/Tenzing_Norgay?

**Comment by pepe** [comment]
I am not sure (as I am not the creator), but I always thought it is him 😉

**Comment by martinklepsch** [comment]
It's a hat tip to an Everest Sherpa named tenzing norgay – if you would
like to add some info to the readme about that I think it would be a nice
addition
