### ISSUE TITLE
Boot source/resource paths

### ISSUE THREAD

**Issue by bsima** [martinklepsch/tenzing#8]
I have no idea why this happens, but when I do `lein new tenzing myapp +reagent +divshot +garden`, a build.boot is generated with the following:

```
(set-env!
 :src-paths   #{"src/cljs" "src/clj"}
 :rsc-paths #{"resources"}
 :dependencies '[[adzerk/boot-cljs      "0.0-2411-3" :scope "test"]
                 [adzerk/boot-cljs-repl "0.1.7"       :scope "test"]
                 [adzerk/boot-reload    "0.2.0"       :scope "test"]
                 [pandeiro/boot-http "0.3.0"]
                 [reagent "0.4.3"]
                 [boot-garden "1.2.5-1"]
                 [cljsjs/react "0.11.2"]])
```

`:src-paths` should be `:source-paths` and `:rsc-paths` should be `:resource-paths`. From a quick look, the code in your repo looks correct, so maybe the lein template is behind a version or two? I have no idea, but I thought I'd mention it. (I spent an embarrassingly long time debugging that lol)

**Comment by martinklepsch** [comment]
@bsima closing this one, if you encountered any other issues, just open another issue :)
