### ISSUE TITLE
out of box sounds

### ISSUE THREAD

**Issue by ashnur** [martinklepsch/tenzing#89]
What if the fastest way to disable all sounds that the tools are making? I already removed `(speak)` from `build.boot`.
I generated the project like this: `boot -d boot/new new -t tenzing -n app-name -a +om-next -a +sass`, but I hope that this is irrelevant and there is a general approach to muting all sounds.

**Comment by martinklepsch** [comment]
@ashnur If you removed all occurrences of `speak` from your `build.boot` there should be no sounds. If there still are any sounds please publish the repo to GitHub and I'll be happy to take a look :)

**Comment by ashnur** [comment]
You are right. Forgot to restart everything after the change.
